### ISSUE TITLE
Provide more inforation on best segmentation workflow

### ISSUE THREAD

**Issue by Lucalino** [orcestra-campaign/flight_segmentation#10]
There might be an optimal way for how to extract segmentation information from the various data sources (flight report, heading, roll angle, ...). E.g. calibration maneuvers often occur on straight legs, so identifying straight legs first and then checking roll angles for calibration might be an efficient sequence of analysis steps. Once we've understood the "optimal" workflow, it would be nice to either add this information to existing notes in the repo or include it in the segmentation template notebook.

**Comment by tmieslinger** [comment]
solved by PR #58
