### ISSUE TITLE
Determine exact EC meeting point

### ISSUE THREAD

**Issue by Lucalino** [orcestra-campaign/flight_segmentation#54]
Exact meeting time with EC should be its own segment. It would be great to come up with some code that determines the exact (3sec interval or so) meeting time between HALO and EC.

**Comment by d70-t** [comment]
No. There's exactly one "meeting point" (in the sense that it's the point on the halo track where the distance between HALO and EarthCare was the shortest). This obviously is not an interval (what length should it have?), but a point and thus needs to be modelled as a different data type, e.g. not a `segment`, but an `event`, just as it was done in EUREC4A.

**Comment by tmieslinger** [comment]
Solved by PR #69
