### ISSUE TITLE
Unnecessary file on main branch

### ISSUE THREAD

**Issue by HF7weatherman** [orcestra-campaign/flight_segmentation#60]
Hi @Lucalino,
I just saw that [your personal segmentation template](https://github.com/orcestra-campaign/flight_segmentation/blob/ab75cbe63e0520cb2b82e023ffaf8a7a0bb67466/scripts/segmentation_template_Luca.ipynb) has been (accidentally) committed to the main branch. Could you please delete it from the main branch?

**Comment by Lucalino** [comment]
Uups... thanks for noticing! I forgot to get rid of it. Will do.
