### ISSUE TITLE
Add information on how to handle missing BAHAMAS data

### ISSUE THREAD

**Issue by Lucalino** [orcestra-campaign/flight_segmentation#9]
Some flights had issues with BAHAMAS and certain data (e.g. roll angle) is not available throughout the flight.
It would be good to come up with a common guideline for how to handle such situations in the flight segmentation process and provide this information in the HALO segmentation notes.

**Comment by d70-t** [comment]
We plan to create a PositionAttitude product on IPFS, which for every flight should contain the best estimate for aircraft position and attitude so far in a common format. Likely that product will help to do the segmentation.

cc @lkluft

**Comment by lkluft** [comment]
There is now a new "position and attitude" dataset available on IPFS. The idea is that it will always contain our "best estimate" of the aircraft position. This means that it includes the BAHAMAS quick look and will be updated to the 100 Hz as soon as it becomes available.

In python, you can use the dataset as follows:
```py
xr.open_zarr("ipns://latest.orcestra-campaign.org/products/HALO/position_attitude/HALO-20240914a.zarr")
```
